base: 'https://typo3-project1-v11.ddev.site/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=46'
  -
    errorCode: 500
    errorHandler: Page
    errorContentSource: 't3://page?uid=46'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    direction: ltr
    flag: de
    websiteTitle: ''
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
websiteTitle: 'Wittemaier Bau GmbH'

routeEnhancers:
  JobsDetail:
    type: Extbase
    limitToPages: 26 # Change this to the pid containing the detail view plugin
    extension: BwJobs
    plugin: Detail
    routes:
      - routePath: '/'
        _controller: 'Frontend::show'
      - routePath: '/{job_position_title}'
        _controller: 'Frontend::show'
        _arguments:
          job_position_title: jobPosition
      - routePath: '/{job_position_title}/apply'
        _controller: 'Frontend::apply'
        _arguments:
          job_position_title: jobPosition
    aspects:
      job_position_title:
        type: PersistedAliasMapper
        tableName: tx_bwjobs_domain_model_jobposition
        routeFieldName: slug
  JobsApi:
    type: Extbase
    extension: BwJobs
    plugin: Api
    routes:
      - routePath: '/api/jobPositions'
        _controller: 'Api::listJobPositions' 
